// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlopbvokkreyoakfplvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsb3Bidm9ra3JleW9ha2ZwbHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0OTQ1MzAsImV4cCI6MjA1NzA3MDUzMH0.DnvoFejrLTDJW6qkWQ0Z7I0K62trawJ4ZzawFq2MUFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);